version: 2

updates:
  - package-ecosystem: "npm"
    directory: "/"
    schedule:
      interval: daily
      time: "00:00"
      timezone: "Etc/UTC"

  # Maintain dependencies for Docker
  - package-ecosystem: "docker"
    directory: "/"
    schedule:
      interval: weekly
    assignees:
      - "fredclausen"

  # Maintain dependencies for GitHub Actions
  - package-ecosystem: "github-actions"
    directory: "/"
    schedule:
      interval: "daily"
    assignees:
      - "fredclausen"
